### ISSUE TITLE
[Feature requset] Flatpak support

### ISSUE THREAD

**Issue by corndog2000** [AdnanHodzic/auto-cpufreq#125]
I am using Fedora Silverblue and would love to be able to install auto-cpufreq from the software center via Flatpak. Have you considered building a flatpak package?

**Comment by AdnanHodzic** [comment]
Of course, this topic has been discussed in #71 and unfortunately it seems it's not possible due to [Flatpak limitations.](https://github.com/AdnanHodzic/auto-cpufreq/issues/71#issuecomment-685224661)
