### ISSUE TITLE
Python pip not updated on opensuse Leap

### ISSUE THREAD

**Issue by NJOYSoftware** [AdnanHodzic/auto-cpufreq#136]
Hi, while installing auto-cpufreq on an fresh opensuse leap (with #135 installer script), I stumbled on the following warning:
```
You are using pip version 10.0.1, however version 20.3.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Could it be useful to check updates for pip in the install script?

**Comment by AdnanHodzic** [comment]
Absolutely as long as it doesn't introduce any additional complexity and introduces new problems.

**Comment by AdnanHodzic** [comment]
Fixed as part of I'm closing this issue, as part of [1.5.2 release](https://github.com/AdnanHodzic/auto-cpufreq/releases/tag/v1.5.2).
