### ISSUE TITLE
Can you add a way to install this without pip? (non systemd support)

### ISSUE THREAD

**Issue by FrostKnight** [AdnanHodzic/auto-cpufreq#199]
My distro has blacklisted pip  but I wanted to see if this really saves as much battery power as you claim. :)

Also, python-distro won't install, so I cannot use it for that reason either. 

I am using a distro without systemd, I will also add.

Hyperbola aka... 

Can you make it possible to use make to install this and not require these two depends.

python-distro
python-setuptools
also pip as well if possible. 

If you make it possible to build with make instead of those two and pip, I could probably use it.

**Comment by AdnanHodzic** [comment]
You can install it from [Snap store](https://github.com/AdnanHodzic/auto-cpufreq#snap-store) or [AUR store](https://github.com/AdnanHodzic/auto-cpufreq#aur-package-archmanjaro-linux) depending on which distribution you're running.

**Comment by FrostKnight** [comment]
Snap store and flatpak and pip are not options in general for my distro, not sure about appimage, but yeah, 

cmake and make would work,  but those above options are excluded...

I tried AUR, but that failed. As odd as it sounds...

**Comment by AdnanHodzic** [comment]
Which distribution are you using?

**Comment by FrostKnight** [comment]
my distro is Hyperbola actually.

**Comment by AdnanHodzic** [comment]
> I tried AUR, but that failed. As odd as it sounds...

It seems like problem is that you're distro doesn't have systemd. 

Note to myself: related #29, #200

**Comment by FrostKnight** [comment]
Yeah, if you could make a package that is a bit more simplistic, doesn't require pip, etc... that would help.

I can install bleachbit easily enough, even the new version and it doesn't require pip.  
But it does have a python like installation method. Just, without pip... obviously. :)

**Comment by AdnanHodzic** [comment]
Yep, this become highest priority for next release.

**Comment by Michael-AU** [comment]
If I may add to this discussion the requirement for systemd is a problem for quite a few distros (e.g. MX, Devuan, just to name 2 Debian based distros). I run Debian Buster without systemd as PID 1 and auto-cpufreq won't work even though it installs. I'm trying to build my own Debian based distro that the user has the option to not use systemd and I would really like to be able to have auto-cpufreq as part of it.

**Comment by FrostKnight** [comment]
Cool, sounds awesome, thanks! I hope you will support runit and openrc and s6 too! :)

I mostly look forward to runit, because it is mega lightweight. :)

**Comment by AdnanHodzic** [comment]
@FrostKnight #235 was just merged with master which adds support for Void Linux (runit)

**Comment by FrostKnight** [comment]
That's good, thanks. :)

**Comment by AdnanHodzic** [comment]
I suggest to install it using [Snap package](https://github.com/AdnanHodzic/auto-cpufreq#snap-store)? As it runs in a container and isolates its Python env from your env. so you shouldn't experience Python related errors.

In meantime I'm closing the issue since it seems to be resolved, please re-open it if the problem persists.
