### ISSUE TITLE
[Request] Add support for artix (non systemd support)

### ISSUE THREAD

**Issue by Juliaria08** [AdnanHodzic/auto-cpufreq#200]
### Error output:
```text
Systemd is not installed, wont work
```
Consider supporting [Artix Linux](https://artixlinux.org/)

**Comment by AdnanHodzic** [comment]
Related: #29

**Comment by AdnanHodzic** [comment]
Support for Artix has been added as part of #237. 

Please pull the latest changes and perform install using [auto-cpufreq-installer](https://github.com/AdnanHodzic/auto-cpufreq/#auto-cpufreq-installer)

**Comment by AdnanHodzic** [comment]
Problem fixed again as part of: #706
