### ISSUE TITLE
Settings do not save

### ISSUE THREAD

**Issue by jgsource** [AdnanHodzic/auto-cpufreq#228]
When I set cpufreq to be powersave, and restart my machine, it randomly switches to on demand. Is there a way to make it use power save every session?

**Comment by AdnanHodzic** [comment]
Yes, please [read the README](https://github.com/AdnanHodzic/auto-cpufreq/blob/master/README.md#install---auto-cpufreq-daemon) or [watch the Youtube video](https://www.youtube.com/watch?v=QkYRpVEEIlg).
