### ISSUE TITLE
Tuned overlap

### ISSUE THREAD

**Issue by mhalano** [AdnanHodzic/auto-cpufreq#290]
I did the same question for thermald, now I ask for tuned. There is any overlap between two solutions? auto-cpufreq was projected to replace TLP, but there is any problem to use with tuned?

**Comment by AdnanHodzic** [comment]
No overlap, they should work fine in tandem.

**Comment by dutrajulio** [comment]
I tested "tuned" today and now it appears to be incompatible with "auto-cpufreq".

Maybe something in the new release, v2.23.0, of "tuned".

Anyone can confirm this too?

**Comment by yabo-boye** [comment]
I have also not been succesful in making those two programs overlap!

**Comment by AdnanHodzic** [comment]
> I have also not been succesful in making those two programs overlap!

@yabo-boye Why are the exact issues are experiencing when using both?
