### ISSUE TITLE
auto-cpufreq --log seems stopped after resume

### ISSUE THREAD

**Issue by validatedev** [AdnanHodzic/auto-cpufreq#31]
Cannot reopen https://github.com/AdnanHodzic/auto-cpufreq/issues/6 myself, so opening the issue again. After suspending and resuming the laptop causes stopping `auto-cpufreq --log` output. It freezes.

**Comment by validatedev** [comment]
Output of `systemctl status auto-cpufreq`
```
● auto-cpufreq.service - auto-cpufreq - Automatic CPU speed & power optimizer f>
     Loaded: loaded (/etc/systemd/system/auto-cpufreq.service; enabled; vendor >
     Active: active (running) since Sat 2020-01-11 11:34:22 +03; 52min ago
   Main PID: 1811 (python3)
      Tasks: 1 (limit: 9195)
     Memory: 17.8M
     CGroup: /system.slice/auto-cpufreq.service
             └─1811 /usr/bin/python3 /usr/bin/auto-cpufreq --daemon

```

**Comment by validatedev** [comment]
FYI, `sudo python3 auto-cpufreq.py --log` also seems stopped.

**Comment by Exorust** [comment]
This is possibly because of saving the .service file in /lib directory instead of the /usr/lib directory.

**Comment by validatedev** [comment]
> This is possibly because of saving the .service file in /lib directory instead of the /usr/lib directory.

Do you have have a source for that, or just an intuition?

**Comment by Exorust** [comment]
Unfortunately only an intuition, I can't track down where the log is being saved. The logging info is being saved. I can verify that through, `systemctl status auto-cpufreq -n20`. But still `auto-cpufreq --log` doesn't work. 

Apart from that, I have also experimented with changing the `service` file and making the following edits,
```
StandardOutput=append:/var/log/auto-cpufreq.log
```
Still no result.

**Comment by AdnanHodzic** [comment]
@Exorust can you update me [with what I suggested](https://github.com/AdnanHodzic/auto-cpufreq/issues/6#issuecomment-573389224) in #6

**Comment by Exorust** [comment]
Its empty

**Comment by AdnanHodzic** [comment]
Then something is terribly wrong. Can you tell me what distro are you using, along with Python version and version for psutil, click, power packages.

**Comment by validatedev** [comment]
That command sometimes freezes, sometimes works. Interesting.

**Comment by validatedev** [comment]
We can do something with the changes on the .py file. Will trying to redirect the stdout to log file directly.

**Comment by validatedev** [comment]
@AdnanHodzic Could you reproduce the issue with `systemctl restart auto-cpufreq.service` command?

**Comment by validatedev** [comment]
@Exorust Could you have a chance for trying the PR?

**Comment by Exorust** [comment]
> Then something is terribly wrong. Can you tell me what distro are you using, along with Python version and version for psutil, click, power packages.

I'm using Ubuntu 16.04, psutil 5.4.8, click 7.0, power 1.4 and python 3.5.2

**Comment by AdnanHodzic** [comment]
Can everyone who has this problem, run following:

```
sudo auto-cpufreq --remove
git checkout -b validatedev-fix-file-log master
git pull https://github.com/validatedev/auto-cpufreq.git fix-file-log
sudo python3 auto-cpufreq.py --install
auto-cpufreq --log
```

and see if you still have logs stopping after suspend/hibernate.

**Comment by smarambas** [comment]
@AdnanHodzic I had the same problem with the logs freezing but after applying @validatedev's fix it seems to work again after suspend/hibernate. Just to know, I'm using Fedora 31, python 3.7.6, psutil 5.6.3, click 7.0 and power 1.4.
Anyway, thanks for this nice tool.

**Comment by paulhewson** [comment]
> Can everyone who has this problem, run following:
> 
> ```
> sudo auto-cpufreq --remove
> git checkout -b validatedev-fix-file-log master
> git pull https://github.com/validatedev/auto-cpufreq.git fix-file-log
> sudo python3 auto-cpufreq.py --install
> auto-cpufreq --log
> ```
> 
> and see if you still have logs stopping after suspend/hibernate.

Hi, I have the same issue with logs here (Ubuntu 19.10 - python3 3.7.5-1).
Tried the fix you're suggesting but I have some problems with the validatedev git repo

```
alessandro@Ale:~$ git checkout -b validatedev-fix-file-log master
fatal: not a git repository (or any of the parent directories): .git
alessandro@Ale:~$ git pull https://github.com/validatedev/auto-cpufreq.git fix-file-log
fatal: not a git repository (or any of the parent directories): .git
```

**Comment by validatedev** [comment]
> > Can everyone who has this problem, run following:
> > ```
> > sudo auto-cpufreq --remove
> > git checkout -b validatedev-fix-file-log master
> > git pull https://github.com/validatedev/auto-cpufreq.git fix-file-log
> > sudo python3 auto-cpufreq.py --install
> > auto-cpufreq --log
> > ```
> > 
> > 
> > and see if you still have logs stopping after suspend/hibernate.
> 
> Hi, I have the same issue with logs here (Ubuntu 19.10 - python3 3.7.5-1).
> Tried the fix you're suggesting but I have some problems with the validatedev git repo
> 
> ```
> alessandro@Ale:~$ git checkout -b validatedev-fix-file-log master
> fatal: not a git repository (or any of the parent directories): .git
> alessandro@Ale:~$ git pull https://github.com/validatedev/auto-cpufreq.git fix-file-log
> fatal: not a git repository (or any of the parent directories): .git
> ```

I deleted the repo. Let me create again.

**Comment by validatedev** [comment]
@paulhewson and everyone, please try this:
```
sudo auto-cpufreq --remove
mkdir validatedev-auto-cpufreq
cd validatedev-auto-cpufreq
git clone https://github.com/validatedev/auto-cpufreq.git
cd auto-cpufreq
sudo python3 auto-cpufreq.py --install
auto-cpufreq --log
```

**Comment by paulhewson** [comment]
Ok, thanks, I have downloaded your repo, so now I'm going to suspend my laptop, resume it and see if logs for auto-cpufreq work.
One curiosity: so your repo is basically this auto-cpufreq with the addition of this fix for log files, isn't it?

**Comment by validatedev** [comment]
> Ok, thanks, I have downloaded your repo, so now I'm going to suspend my laptop, resume it and see if logs for auto-cpufreq work.
> One curiosity: so your repo is basically this auto-cpufreq with the addition of this fix for log files, isn't it?

Yes, it is just this. In addition, in new version that fix has been merged (in snap branch). You can safely continue to use my repo until the new version of the program appears.

**Comment by AdnanHodzic** [comment]
@validatedev thank you for your assistance. 

@paulhewson I've merged all the changes which were made as part of `snap` package into `master`. Please pull the latest changes.

Since this problem is now fixed, I'll close this bug report.
