### ISSUE TITLE
Got problem while installation

### ISSUE THREAD

**Issue by RanjanPH** [AdnanHodzic/auto-cpufreq#310]
Mount snap "auto-cpufreq" (91) (installation not allowed by "etc-auto-cpufreq-conf" plug rule of interface "system-files" for "auto-cpufreq" snap)
![Screenshot from 2021-12-16 08-03-52](https://user-images.githubusercontent.com/85860710/146295915-877f9ad1-0eca-4ca1-be83-bc43fa78fc09.png)

**Comment by AdnanHodzic** [comment]
This problem has just been resolved as part of auto-cpufreq 1.8.1 (93 revision). Please feel free to re-open the issue or comment if the problem persists.
