### ISSUE TITLE
incorrect max freq - debian unstable (02-2022)

### ISSUE THREAD

**Issue by konsantinst** [AdnanHodzic/auto-cpufreq#364]
### Error output:
```cpu freq showing incorrect  "Frequency"
Add/paste error output
```
Incorrect current cpu freq.

                        "auto-cpufreq" refresh in: 1
                Executed on: February 19 (Saturday) - 00:08:37

-------------------------------------------------------------------------------

Linux distro: Debian GNU/Linux unstable sid
Linux kernel: 5.15.0-3-amd64
Processor: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
Cores: 16
Architecture: x86_64
Driver: intel_pstate

------------------------------ Current CPU stats ------------------------------

CPU max frequency: 850 MHz
CPU min frequency: 800 MHz

Core    Usage   Temperature     Frequency
CPU0:     6.2%     44 °C     2300 MHz
CPU1:     6.1%     45 °C     2300 MHz
CPU2:     2.0%     44 °C     2300 MHz
CPU3:     6.0%     48 °C     2300 MHz
CPU4:     9.7%     46 °C     2300 MHz
CPU5:     3.0%     45 °C     2300 MHz
CPU6:     2.0%     48 °C     2300 MHz
CPU7:     2.0%     45 °C      800 MHz
CPU8:     2.0%     44 °C     2300 MHz
CPU9:     2.9%     45 °C     2300 MHz
CPU10:    8.0%     44 °C     2300 MHz
CPU11:    3.9%     48 °C     2300 MHz
CPU12:    0.0%     46 °C     2300 MHz
CPU13:    0.0%     45 °C     2300 MHz
CPU14:   11.8%     48 °C     2300 MHz
CPU15:    4.1%     45 °C     2300 MHz

---------------------------- CPU frequency scaling ----------------------------

Battery is: discharging

Setting to use: "powersave" governor

Total CPU usage: 5.2 %
Total system load: 1.75
Average temp. of all cores: 45.625 °C
Configuration file disables turbo boost
setting turbo boost: off

-------------------------------------------------------------------------------

                        "auto-cpufreq" refresh in: 1
                Executed on: February 19 (Saturday) - 00:08:44

-------------------------------------------------------------------------------

Linux distro: Debian GNU/Linux unstable sid
Linux kernel: 5.15.0-3-amd64
Processor: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
Cores: 16
Architecture: x86_64
Driver: intel_pstate

------------------------------ Current CPU stats ------------------------------

CPU max frequency: 850 MHz
CPU min frequency: 800 MHz

Core    Usage   Temperature     Frequency
CPU0:     1.1%     44 °C     2300 MHz
CPU1:     1.0%     44 °C     2300 MHz
CPU2:     2.0%     44 °C      800 MHz
CPU3:     2.0%     48 °C      800 MHz
CPU4:     6.8%     46 °C     2300 MHz
CPU5:     3.0%     45 °C     2300 MHz
CPU6:     4.9%     47 °C      800 MHz
CPU7:     5.0%     45 °C     2300 MHz
CPU8:     9.8%     44 °C      800 MHz
CPU9:     8.0%     44 °C     2300 MHz
CPU10:    8.1%     44 °C     2300 MHz
CPU11:    2.0%     48 °C     2300 MHz
CPU12:    4.9%     46 °C     2300 MHz
CPU13:    8.0%     45 °C     2300 MHz
CPU14:    5.8%     47 °C     2300 MHz
CPU15:    5.1%     45 °C     2300 MHz

---------------------------- CPU frequency scaling ----------------------------

Battery is: discharging

Setting to use: "powersave" governor

Total CPU usage: 5.6 %
Total system load: 1.48
Average temp. of all cores: 45.375 °C
Configuration file disables turbo boost
setting turbo boost: off

-------------------------------------------------------------------------------

                        "auto-cpufreq" refresh in: 4

At the same time i7s (and pretty much every other program) is reporting as it is set (and auto-cpufreq is showing whats max cpufreq) - max 850 Mhz...

Cpu speed from cpuinfo 2303.00Mhz
cpuinfo might be wrong if cpufreq is enabled. To guess correctly try estimating via tsc
Linux's inbuilt cpu_khz code emulated now
True Frequency (without accounting Turbo) 2304 MHz
  CPU Multiplier 23x || Bus clock frequency (BCLK) 100.17 MHz

Socket [0] - [physical cores=8, logical cores=16, max online cores ever=8]
  TURBO ENABLED on 8 Cores, Hyper Threading ON
  Max Frequency without considering Turbo 2404.17 MHz (100.17 x [24])
  Max TURBO Multiplier (if Enabled) with 1/2/3/4/5/6 Cores is  46x/46x/45x/45x/45x/44x
  Real Current Frequency 797.85 MHz [100.17 x 7.96] (Max of below)
        Core [core-id]  :Actual Freq (Mult.)      C0%   Halt(C1)%  C3 %   C6 %  Temp      VCore
        Core 1 [0]:       797.68 (7.96x)        9.33    96.8       0       0    45      0.6699
        Core 2 [1]:       797.83 (7.96x)        14.9    94.8       0       0    46      0.6699
        Core 3 [2]:       797.85 (7.96x)        8.25    97.1       0       0    44      0.6749
        Core 4 [3]:       797.65 (7.96x)        5.72      98       0       0    50      0.6625
        Core 5 [4]:       797.80 (7.96x)        5.92      98       0       0    48      0.6725
        Core 6 [5]:       797.82 (7.96x)        3.83    98.7       0       0    46      0.6725
        Core 7 [6]:       797.69 (7.96x)        6.33    97.8       0       0    48      0.6549
        Core 8 [7]:       797.77 (7.96x)        20.1      93       0       0    46      0.6649
C1 = Processor running with halts (States >C0 are power saver modes with cores idling)
C3 = Cores running with PLL turned off and core cache turned off
C6, C7 = Everything in C3 + core state saved to last level cache, C7 is deeper than C6
  Above values in table are in percentage over the last 1 sec
[core-id] refers to core-id number in /proc/cpuinfo
'Garbage Values' message printed when garbage values are read
  Ctrl+C to exit

Not  a big issue in general, just noticed that :-)

Cheers
K
---

### System information:

Add/paste output of:

```
auto-cpufreq --debug

oot@kkd:~/auto-cpufreq# auto-cpufreq --debug

Using settings defined in /etc/auto-cpufreq.conf file

-------------------------------------------------------------------------------

Linux distro: Debian GNU/Linux unstable sid
Linux kernel: 5.15.0-3-amd64
Processor: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
Cores: 16
Architecture: x86_64
Driver: intel_pstate

------------------------------ Current CPU stats ------------------------------

CPU max frequency: 850 MHz
CPU min frequency: 800 MHz

Core    Usage   Temperature     Frequency
CPU0:     7.9%     45 °C     2300 MHz
CPU1:     1.0%     45 °C     2300 MHz
CPU2:     6.7%     46 °C     2300 MHz
CPU3:     8.0%     49 °C     2300 MHz
CPU4:    12.1%     47 °C     2300 MHz
CPU5:     1.0%     46 °C     2300 MHz
CPU6:     4.0%     48 °C     2300 MHz
CPU7:     1.0%     45 °C     2300 MHz
CPU8:     3.0%     45 °C     2300 MHz
CPU9:     3.0%     45 °C     2300 MHz
CPU10:    5.8%     46 °C     2300 MHz
CPU11:   11.0%     49 °C     2300 MHz
CPU12:    7.1%     47 °C     2300 MHz
CPU13:    7.9%     46 °C     2300 MHz
CPU14:    7.0%     48 °C     2300 MHz
CPU15:    1.0%     45 °C      800 MHz

auto-cpufreq version: 1.9.1 (git: 8fb5469a)

Python: 3.9.10
psutil package: 5.9.0
platform package: 1.0.8
click package: 8.0.3
distro package: 1.6.0

Computer type: Notebook
Battery is: discharging

auto-cpufreq system resource consumption:
cpu usage: 0.0 %
memory use: 0.07 %

Total CPU usage: 4.7 %
Total system load: 1.44
Average temp. of all cores: 46.375 °C 

Currently using: powersave governor
Currently turbo boost is: off

-------------------------------------------------------------------------------


```

#### Without providing requested information your issue might be ignored!

---

**Comment by AdnanHodzic** [comment]
Just [released v1.9.2](https://github.com/AdnanHodzic/auto-cpufreq/releases) which adds ability to change power governor used by default with auto-cpufreq from `balanced` to `performance` [using power_helper.py script](https://github.com/AdnanHodzic/auto-cpufreq/#1-power_helperpy-script). Curious to hear if you still have same problem if you switch to `performance` governor?

**Comment by konsantinst** [comment]
hm, thats Interesting, still acting the same way ... odd...




oot@kkd:~/auto-cpufreq# grep "battery power" -A26 /etc/auto-cpufreq.conf 
# settings for when using battery power
[battery]
# see available governors by running: cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors
# preferred governor
#governor = powersave
governor = performance 

# minimum cpu frequency (in kHz)
# example: for 800 MHz = 800000 kHz --> scaling_min_freq = 800000
# see conversion info: https://www.rapidtables.com/convert/frequency/mhz-to-hz.html
# to use this feature, uncomment the following line and set the value accordingly
# scaling_min_freq = 800000
scaling_min_freq = 800000

# maximum cpu frequency (in kHz)
# see conversion info: https://www.rapidtables.com/convert/frequency/mhz-to-hz.html
# example: for 1GHz = 1000 MHz = 1000000 kHz -> scaling_max_freq = 1000000
# to use this feature, uncomment the following line and set the value accordingly
# scaling_max_freq = 1000000
scaling_max_freq = 850000

# turbo boost setting. possible values: always, auto, never
turbo = never

root@kkd:~/auto-cpufreq# 






root@kkd:~/auto-cpufreq# systemctl restart auto-cpufreq


root@kkd:~/auto-cpufreq# systemctl status auto-cpufreq
● auto-cpufreq.service - auto-cpufreq - Automatic CPU speed & power optimizer for Linux
     Loaded: loaded (/etc/systemd/system/auto-cpufreq.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2022-02-25 20:13:04 EET; 34s ago
   Main PID: 2631509 (python)
      Tasks: 1 (limit: 38156)
     Memory: 15.8M
        CPU: 627ms
     CGroup: /system.slice/auto-cpufreq.service
             └─2631509 /opt/auto-cpufreq/venv/bin/python /opt/auto-cpufreq/venv/bin/auto-cpufreq --daemon

Feb 25 20:13:04 kkd systemd[1]: Started auto-cpufreq - Automatic CPU speed & power optimizer for Linux.
Feb 25 20:13:04 kkd python[2631511]: sh: 1: snap: not found
root@kkd:~/auto-cpufreq# 






Linux distro: Debian GNU/Linux unstable sid
Linux kernel: 5.15.0-3-amd64
Processor: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
Cores: 16
Architecture: x86_64
Driver: intel_pstate

------------------------------ Current CPU stats ------------------------------

CPU max frequency: 850 MHz
CPU min frequency: 800 MHz

Core    Usage   Temperature     Frequency
CPU0:     0.0%     45 °C     2300 MHz
CPU1:     0.0%     46 °C     2300 MHz
CPU2:     0.0%     44 °C     2300 MHz
CPU3:     1.0%     49 °C     2300 MHz
CPU4:     0.0%     47 °C     2300 MHz
CPU5:     1.0%     45 °C     2300 MHz
CPU6:     1.0%     48 °C     2300 MHz
CPU7:     0.0%     45 °C     2300 MHz
CPU8:     0.0%     45 °C     2300 MHz
CPU9:     0.0%     46 °C     2300 MHz
CPU10:    1.0%     44 °C     2300 MHz
CPU11:    1.0%     49 °C      800 MHz
CPU12:    0.0%     47 °C      800 MHz
CPU13:    1.0%     45 °C     2300 MHz
CPU14:    0.0%     48 °C     2300 MHz
CPU15:    0.0%     45 °C     2300 MHz

---------------------------- CPU frequency scaling ----------------------------

Battery is: discharging

Setting to use: "performance" governor

Total CPU usage: 0.3 %
Total system load: 0.37
Average temp. of all cores: 46.125 °C
Configuration file disables turbo boost
setting turbo boost: off

-------------------------------------------------------------------------------

                        "auto-cpufreq" refresh in: 1








root@kkd:~/auto-cpufreq# auto-cpufreq --debug
sh: 1: snap: not found

Using settings defined in /etc/auto-cpufreq.conf file

-------------------------------------------------------------------------------

Linux distro: Debian GNU/Linux unstable sid
Linux kernel: 5.15.0-3-amd64
Processor: 11th Gen Intel(R) Core(TM) i7-11800H @ 2.30GHz
Cores: 16
Architecture: x86_64
Driver: intel_pstate

------------------------------ Current CPU stats ------------------------------

CPU max frequency: 850 MHz
CPU min frequency: 800 MHz

Core    Usage   Temperature     Frequency
CPU0:     0.0%     45 °C      800 MHz
CPU1:     0.0%     47 °C     2300 MHz
CPU2:     0.0%     44 °C     2300 MHz
CPU3:     5.0%     49 °C     2300 MHz
CPU4:     8.6%     47 °C     2300 MHz
CPU5:     1.0%     45 °C     2300 MHz
CPU6:     1.0%     47 °C     2300 MHz
CPU7:     1.0%     45 °C     2300 MHz
CPU8:     0.0%     45 °C     2300 MHz
CPU9:     1.0%     47 °C     2300 MHz
CPU10:    0.0%     44 °C     2300 MHz
CPU11:    2.0%     49 °C     2300 MHz
CPU12:    1.0%     47 °C     2300 MHz
CPU13:    0.0%     45 °C     2300 MHz
CPU14:    0.0%     47 °C     2300 MHz
CPU15:    0.0%     45 °C     2300 MHz

auto-cpufreq version: 1.9.2 (git: f65dba36)

Python: 3.9.10
psutil package: 5.9.0
platform package: 1.0.8
click package: 8.0.3
distro package: 1.6.0

Computer type: Notebook
Battery is: discharging

auto-cpufreq system resource consumption:
cpu usage: 0.0 %
memory use: 0.07 %

Total CPU usage: 3.0 %
Total system load: 0.75
Average temp. of all cores: 46.125 °C 

Currently using: performance governor
Currently turbo boost is: off

-------------------------------------------------------------------------------

root@kkd:~/auto-cpufreq#

**Comment by konsantinst** [comment]
sorry for this ridicules formatting, still a rookie on gh :-(

**Comment by sizuf** [comment]
Can you run those commands and tell the output? 

`cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq 
`
`cat /sys/devices/system/cpu/cpu0/cpufreq/cpuinfo_max_freq 
`
I'm investigating similar issue on my machine too

**Comment by AdnanHodzic** [comment]
If there are any changes that could be made please give it a try and [contribute to the project](https://github.com/AdnanHodzic/auto-cpufreq/#code-contribution) and you will be credited for your work as part of [future release](https://github.com/AdnanHodzic/auto-cpufreq/releases).

In meantime closing the issue due to inactivity.
