### ISSUE TITLE
Python evnvPackage not foind error

### ISSUE THREAD

**Issue by Fatheem33** [AdnanHodzic/auto-cpufreq#378]
### Error output:
```text
Add/paste error output
```
---

### System information:

Add/paste output of:

```
auto-cpufreq --debug
```

#### Without providing requested information your issue might be ignored!

---

If installation failed with [auto-cpufreq-installer ](https://github.com/AdnanHodzic/auto-cpufreq/#auto-cpufreq-installer)have you tried installing auto-cpufreq using [Snap package](https://github.com/AdnanHodzic/auto-cpufreq/#snap-store)?

**Comment by AdnanHodzic** [comment]
Incorrectly created issue (instructions not followed).
