### ISSUE TITLE
[Suggestion] --stats

### ISSUE THREAD

**Issue by niksingh710** [AdnanHodzic/auto-cpufreq#384]
Usage of the `watch` command for the `--stats` instead of cluttering the output every 5 sec will be a better approach.

**Comment by AdnanHodzic** [comment]
I always advise people to [make their own code contributions](https://github.com/AdnanHodzic/auto-cpufreq/#code-contribution) if they have a good idea how certain things should be done.

**Comment by niksingh710** [comment]
It's not a bug. So closing it.
