### ISSUE TITLE
Can't stop the daemon

### ISSUE THREAD

**Issue by He3dshot** [AdnanHodzic/auto-cpufreq#386]
I tried to stop the daemon with `service auto-cpufreq stop` and it gave me an error saying "Failed to stop auto-cpufreq.service: Unit auto-cpufreq.service not loaded." How can I load auto-cpufreq.service?

**Comment by AdnanHodzic** [comment]
auto-cpufreq automatically starts the service [after install](https://github.com/AdnanHodzic/auto-cpufreq/#install---auto-cpufreq-daemon).
