### ISSUE TITLE
install error

### ISSUE THREAD

**Issue by gaoliuzhu** [AdnanHodzic/auto-cpufreq#390]
### Error output:
```text
error: cannot perform the following tasks:
- Mount snap "auto-cpufreq" (82) (installation not allowed by "etc-auto-cpufreq-conf" plug rule of interface "system-files" for "auto-cpufreq" snap)
```
---

### System information:

cpu: arm7l
ubuntu20.04

#### Without providing requested information your issue might be ignored!
<img width="1266" alt="image" src="https://user-images.githubusercontent.com/52945898/165661821-b4d4520c-bc07-411a-9afb-332a01ebdf1e.png">

**Comment by AdnanHodzic** [comment]
Which version of snap did you install?

**Comment by gaoliuzhu** [comment]
i used manual install and it worked, thank you!
