### ISSUE TITLE
Higher freq than maximum on almost every core

### ISSUE THREAD

**Issue by Lolis4TheWin** [AdnanHodzic/auto-cpufreq#396]
![image](https://user-images.githubusercontent.com/50179148/169655757-70f60f73-11e1-4563-a6fa-100607c6dce7.png)

Manjaro, T480(Intel i5-8350U)
And the --live says that i have tlp running, but i stopped and disabled via systemctl

While doint stress test all the cores on max 3ghz.

**Comment by AdnanHodzic** [comment]
I fail to understand what's the problem then? That auto-cpufreq is allowing you hit frequencies higher then your distribution does? 

Also template when submitting new issue was not filled out which clearly said:

#### Without providing requested information your issue might be ignored!

Hence I'm closing this issue.

**Comment by Lolis4TheWin** [comment]
Sorry for takig your time.
i solved the issue, intel-psstage driver caused, now it is disabled.
