### ISSUE TITLE
Why can it not control frequency with intel_pstate?

### ISSUE THREAD

**Issue by Rabcor** [AdnanHodzic/auto-cpufreq#415]
I noticed that TLP can (e.g. if I configure TLP to set a maximum frequency of 800mhz, all cores will just use 800mhz)

Why can't auto-cpufreq?

**Comment by AdnanHodzic** [comment]
As I mentioned in #416, I'll just repeat my questions here.

Have you seen [configuring auto-cpufreq section of the Readme](https://github.com/AdnanHodzic/auto-cpufreq/#configuring-auto-cpufreq)? In particular the [2: auto-cpufreq config file section](https://github.com/AdnanHodzic/auto-cpufreq/#2-auto-cpufreq-config-file)?

**Comment by Rabcor** [comment]
@AdnanHodzic sorry, i didn't actually know there was a discussions section on github :grimacing:
