### ISSUE TITLE
/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference

### ISSUE THREAD

**Issue by volnes** [AdnanHodzic/auto-cpufreq#46]
Hi!
Got error when use 
`sudo auto-cpufreq --live`

> Setting to use "performance" governor
> /usr/bin/cpufreqctl: row 267: /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_preference: Access denied
> /usr/bin/cpufreqctl: row 267: /sys/devices/system/cpu/cpu1/cpufreq/energy_performance_preference: Access denied
> /usr/bin/cpufreqctl: row 267: /sys/devices/system/cpu/cpu2/cpufreq/energy_performance_preference: Access denied
> /usr/bin/cpufreqctl: row 267: /sys/devices/system/cpu/cpu3/cpufreq/energy_performance_preference: Access denied

I check that files and they doesn't exist....
Ubuntu 18.04.4

**Comment by AdnanHodzic** [comment]
Did you use `auto-cpufreq-installer` to install?

**Comment by volnes** [comment]
> auto-cpufreq-installer
this

**Comment by AdnanHodzic** [comment]
@validatedev any idea on this one? Seems to be related to [latest changes to `cpufreqctl` file.](https://github.com/AdnanHodzic/auto-cpufreq/pull/45)

**Comment by validatedev** [comment]
@AdnanHodzic Will look at it asap.

**Comment by validatedev** [comment]
@volnes Could you have a chance for letting the CPU model to us please?

**Comment by volnes** [comment]
Intel i5-2540M @ 3.300GHz

**Comment by validatedev** [comment]
I suspect that older CPU's are not support EPP, which is Intel SpeedShift on Windows. Making some changes and let you try @volnes

**Comment by validatedev** [comment]
I wanna sure about the absence of the parameters, @volnes could you try `cat /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences` please?

**Comment by volnes** [comment]
> cat /sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences

as i say early, there no such file...

![image](https://user-images.githubusercontent.com/5400851/77457360-9d3ef300-6e0d-11ea-8b2c-952bb1388e46.png)

**Comment by AdnanHodzic** [comment]
@validatedev perhaps the simplest thing to do (altough it's bit of a hack), would be to add a file check for:

- `/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences`
- `/sys/devices/system/cpu/cpu0/cpufreq/energy_performance_available_preferences`

If one of the  files isn't there simply skip run of `s.run("cpufreqctl --epp --set=balance_power", shell=True) ` in `core.py`.

Unless you have some other more elegant solution :)

**Comment by validatedev** [comment]
@AdnanHodzic yeah that's what I'm doing right now :)

**Comment by AdnanHodzic** [comment]
:+1: looking forward to PR then :)

**Comment by validatedev** [comment]
@volnes 
Could you try https://github.com/validatedev/auto-cpufreq/tree/fix-conflict-with-TLP because I want to sure about my fix is working.

**Comment by volnes** [comment]
@validatedev 
![image](https://user-images.githubusercontent.com/5400851/77460221-de390680-6e11-11ea-8b3b-4f069761309e.png)
i think all ok, no errors

**Comment by AdnanHodzic** [comment]
@validatedev I made some comments as there are code conflicts in #47 

Could you please look into them as I'd like to merge these changes ASAP as it's a serious bug and I want to release new version of snap including these changes as well.

Thanks

**Comment by AdnanHodzic** [comment]
@volnes problem has been fixed as part of #48 PR. Please pull the latest changes and re-install the tool. 

Please feel free to re-open the issue if you're still experiencing the same issue.

**Comment by volnes** [comment]
@AdnanHodzic @validatedev  yes update, problem fixed, thanks guys for your work
