### ISSUE TITLE
[Question / Feature Request] CPU Fan Speed Control

### ISSUE THREAD

**Issue by ChickenIQ** [AdnanHodzic/auto-cpufreq#491]
Is there any way to set a minimum CPU fan speed bellow a certain temperature?

I'm currently trying to achieve having a completely silent fan while the CPU is at a low temperature.

My current CPU fan speed is at 2500 RPM at 30 °C avg temp of all cores and I can't seem to go lower than that.

**Comment by shadeyg56** [comment]
Your CPU fan is controlled by your laptop's BIOS

You will have to check yours to see if there's an option to control the fan speed. Unfortunately, you can't control it through software
