### ISSUE TITLE
Incorrect temperatures

### ISSUE THREAD

**Issue by pimpmyname2** [AdnanHodzic/auto-cpufreq#498]
### Have you tried?

- [Searching through existing/closed issues](https://github.com/AdnanHodzic/auto-cpufreq/issues) to see if your bug has already been already submitted?
Yes.
 
- If installation failed with [auto-cpufreq-installer](https://github.com/AdnanHodzic/auto-cpufreq/#auto-cpufreq-installer),have you tried installing auto-cpufreq using [Snap package](https://github.com/AdnanHodzic/auto-cpufreq/#snap-store)?
No. Installation succeeded.

- Have you tried [configuring auto-cpufreq](https://github.com/AdnanHodzic/auto-cpufreq/#configuring-auto-cpufreq)?
Yes.
- Have you tried suggestions in [troubleshooting section](https://github.com/AdnanHodzic/auto-cpufreq#troubleshooting)?
Yes.

### Error output:
```text
No errors.
```
---

### System information:

Add/paste output of:

```
Using settings defined in /etc/auto-cpufreq.conf file

-------------------------------------------------------------------------------

Linux distro: Ubuntu 22.04 Jammy Jellyfish
Linux kernel: 5.19.0-38-generic
Processor: AMD Ryzen Threadripper 2950X 16-Core Processor
Cores: 32
Architecture: x86_64
Driver: acpi-cpufreq

------------------------------ Current CPU stats ------------------------------

CPU max frequency: 3500 MHz
CPU min frequency: 2800 MHz

Core    Usage   Temperature     Frequency
CPU0:     0.0%     26 °C     2226 MHz
CPU1:     3.0%     26 °C     2224 MHz
CPU2:     1.0%     26 °C     2224 MHz
CPU3:     1.0%     26 °C     3122 MHz
CPU4:     1.0%     26 °C     2727 MHz
CPU5:     0.0%     26 °C     4098 MHz
CPU6:     0.0%     26 °C     2212 MHz
CPU7:     1.0%     26 °C     2704 MHz
CPU8:    11.0%     26 °C     2796 MHz
CPU9:     0.0%     26 °C     2800 MHz
CPU10:    8.0%     26 °C     2794 MHz
CPU11:    4.0%     26 °C     2794 MHz
CPU12:    1.0%     26 °C     2793 MHz
CPU13:    0.0%     26 °C     2800 MHz
CPU14:    1.0%     26 °C     2800 MHz
CPU15:    4.0%     26 °C     2794 MHz
CPU16:    0.0%     26 °C     2211 MHz
CPU17:    1.0%     26 °C     2221 MHz
CPU18:    0.0%     26 °C     2220 MHz
CPU19:   13.9%     26 °C     3208 MHz
CPU20:    1.0%     26 °C     2712 MHz
CPU21:    0.0%     26 °C     4092 MHz
CPU22:    2.0%     26 °C     2210 MHz
CPU23:    3.0%     26 °C     2733 MHz
CPU24:    5.1%     26 °C     2798 MHz
CPU25:    0.0%     26 °C     2794 MHz
CPU26:    1.0%     26 °C     2794 MHz
CPU27:    9.9%     26 °C     2794 MHz
CPU28:    0.0%     26 °C     2793 MHz
CPU29:    0.0%     26 °C     2795 MHz
CPU30:    4.0%     26 °C     2800 MHz
CPU31:    1.0%     26 °C     2792 MHz

CPU fan speed: 1551 RPM

auto-cpufreq version: 1.9.7 (git: 9912f9d8)

Python: 3.10.6
psutil package: 5.9.4
platform package: 1.0.8
click package: 8.1.3
distro package: 1.8.0

Computer type: Desktop
Battery is: charging

auto-cpufreq system resource consumption:
cpu usage: 0.0 %
memory use: 0.07 %

Total CPU usage: 1.7 %
Total system load: 1.06
Average temp. of all cores: 25.85 °C

Currently using: schedutil governor
Currently turbo boost is: on

-------------------------------------------------------------------------------
```

Also please be descriptive about the issue you're reporting, i.e: what you tried & what's the expected behaviour.

Temperature is incorrect in "auto-cpufreq --monitor". Psutil doesnt seem to recognize k10temp-pci sensor. Using python hwmon import will most likely fix the issue. I have attached a image of "Glances" that shows the real CPU temperature(Tctl) which recognizes k10temp sensor.

![auto-cpufreq debug](https://user-images.githubusercontent.com/79339372/231386002-4fa4d022-7ce0-437d-ac8e-8641326e4891.PNG)
![hwmon_glances](https://user-images.githubusercontent.com/79339372/231386006-80c79575-7eb4-468f-b8d7-21101ef82129.PNG)
![temp_psutil](https://user-images.githubusercontent.com/79339372/231386007-de8cfff3-b926-4990-8cfc-a6b160b4a4fa.PNG)

---

**Comment by AdnanHodzic** [comment]
Changes which should fix this issue have been merged as part of #513, please pull the latest changes and re-install auto-cpufreq. 

If the problem persists, please re-open the issue.
