### ISSUE TITLE
Does this work on immutable distros?

### ISSUE THREAD

**Issue by trytomakeyouprivate** [AdnanHodzic/auto-cpufreq#502]
I see at least in the install script it tries to write to /usr which is read-only on Fedora Immutable, OpenSuse microOS and others. 

The script probably runs in other directories too, can this be easily adapted? The systemd service also tries to execute something there, which also doesnt work.

**Comment by AdnanHodzic** [comment]
This is more of a question then an issue, and as such should be move to [discussions](https://github.com/AdnanHodzic/auto-cpufreq/discussions). Yes, it works on immutable distros, as this functionality (PR's) were implemented by people who are using them and made it work for their distro.
