### ISSUE TITLE
Alternatives, rewrites, similar programs ...

### ISSUE THREAD

**Issue by explosion-mental** [AdnanHodzic/auto-cpufreq#504]
Simply listing projects with similar goals that I was able to find (and write :p) that I think could be better in some scenarios:

- [auto-clock-speed](https://github.com/JakeRoggenbuck/auto-clock-speed) 
- [yablo - Yet Another Battery Linux Optimizer](https://github.com/sebastian-xyz/yablo)
- [racf - Rusty Auto CPU Frequencer](https://github.com/explosion-mental/racf) 
- [sacf - Simple Auto CPU Frequencer](https://github.com/explosion-mental/sacf) (uses config.h)

**Comment by AdnanHodzic** [comment]
Please move this to ["Discussion" section](https://github.com/AdnanHodzic/auto-cpufreq/discussions) as it's not an issue or feature request.
