### ISSUE TITLE
Do I need to uninstall power-profiles-daemon if I use GNOME on Fedora

### ISSUE THREAD

**Issue by JuanH88** [AdnanHodzic/auto-cpufreq#509]
I didn't notice changes, power-profiles-daemon prevents it from working or something?

**Comment by AdnanHodzic** [comment]
auto-cpufreq will automatically remove it as mentioned in[ README](https://github.com/AdnanHodzic/auto-cpufreq/#1-power_helperpy-script-snap-package-install-only). 

Will also close this, as it's not an issue and should be part of [Discussion](https://github.com/AdnanHodzic/auto-cpufreq/discussions) section instead.
