### ISSUE TITLE
Module not found pkg_resources

### ISSUE THREAD

**Issue by conrad-mo** [AdnanHodzic/auto-cpufreq#510]
### Have you tried?

- [Searching through existing/closed issues](https://github.com/AdnanHodzic/auto-cpufreq/issues) to see if your bug has already been already submitted? 
- If installation failed with [auto-cpufreq-installer](https://github.com/AdnanHodzic/auto-cpufreq/#auto-cpufreq-installer),have you tried installing auto-cpufreq using [Snap package](https://github.com/AdnanHodzic/auto-cpufreq/#snap-store)?
- Have you tried [configuring auto-cpufreq](https://github.com/AdnanHodzic/auto-cpufreq/#configuring-auto-cpufreq)?
- Have you tried suggestions in [troubleshooting section](https://github.com/AdnanHodzic/auto-cpufreq#troubleshooting)?

Yes

### Error output:
```text
Traceback (most recent call last):
  File "/opt/auto-cpufreq/venv/bin/auto-cpufreq", line 4, in <module>
    __import__('pkg_resources').run_script('auto-cpufreq==1.9.7+8f343df8', 'auto-cpufreq')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pkg_resources'
```
---

### System information:

Add/paste output of:

```
auto-cpufreq --debug
Traceback (most recent call last):
  File "/opt/auto-cpufreq/venv/bin/auto-cpufreq", line 4, in <module>
    __import__('pkg_resources').run_script('auto-cpufreq==1.9.7+8f343df8', 'auto-cpufreq')
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'pkg_resources'
```

Also please be descriptive about the issue you're reporting, i.e: what you tried & what's the expected behaviour.

---
Not a single auto-cpufreq command is working and I'm not sure why. Setuptools exists and i've tried to reinstall it. I'm using the git aur package at the moment

**Comment by JmbFountain** [comment]
I had the same issue, using the auto-cpufreq-installer script after cloning this repository.

`git pull && sudo ./auto-cpufreq-installer && systemctl restart auto-cpufreq` seems to have fixed this issue

**Comment by AdnanHodzic** [comment]
Closing the issue due to inactivity.
