### ISSUE TITLE
Instruction on how to check daemon status when auto-cpufreq is installed using snap

### ISSUE THREAD

**Issue by innovaitec** [AdnanHodzic/auto-cpufreq#58]
Hi, I would recommend updating your web page and other auto-cpufreq material with the correct instructions on how to check daemon status when snap was used to install auto-cpufreq. The instructions currently posted are not working in that scenario.

auto-cpufreq is amazing, thanks for your time!

**Comment by AdnanHodzic** [comment]
Thank you for your kind words!

When you install `auto-cpufreq` using snap package, you can check daemon status using:

```
systemctl status snap.auto-cpufreq.service.service
```

Also there's just been released a [major new release](https://github.com/AdnanHodzic/auto-cpufreq/releases/tag/1.2), so make sure to upgrade :)

Closing the issue, please feel free to re-open it.
