### ISSUE TITLE
auto-cpufreq install instructions are incomplete

### ISSUE THREAD

**Issue by hoshi411** [AdnanHodzic/auto-cpufreq#594]
Since uninstalling TLP is required for running auto-cpufreq correctly, it is NECESSARY  to include TLP uninstall instructions in the installation instructions.

Please do.

**Comment by AdnanHodzic** [comment]
This is already done, auto-cpufreq readme states

> "Please note: auto-cpufreq aims to replace TLP in terms of functionality, so after you install auto-cpufreq _it's recommended to remove TLP._ "

and even in [code output will be made](https://github.com/AdnanHodzic/auto-cpufreq/blob/4ddff1f7026fa6bc4969eb37154b6c431f089120/auto_cpufreq/power_helper.py#L58) once it's detected that TLP is installed:

>Detected you are running a TLP service!
>This daemon might interfere with auto-cpufreq which can lead to unexpected results.
>We strongly encourage you to remove TLP unless you really know what you are doing.

Hence I'm closing this issue.
