### ISSUE TITLE
Is there a reason that the program relies on running inside a virtual environment?

### ISSUE THREAD

**Issue by MusicalArtist12** [AdnanHodzic/auto-cpufreq#608]

**Comment by shadeyg56** [comment]
virtual environments make managing the dependencies easier and prevents conflicts. for example, if somebody has another program that requires a different version of a package we use, there would be a conflict.

**Comment by MusicalArtist12** [comment]
ok that makes sense. I was just packaging the program for arch and there isn't a great way to rely on a virtual environment. I'll make sure that version requirements match the aur build system.
