### ISSUE TITLE
Lenovo L512 - min CPU frequency seems higher than expected.

### ISSUE THREAD

**Issue by mholl1983** [AdnanHodzic/auto-cpufreq#633]
### Have you tried?

- [Searching through existing/closed issues](https://github.com/AdnanHodzic/auto-cpufreq/issues) to see if your bug has already been already submitted? Yes
- If installation failed with [auto-cpufreq-installer](https://github.com/AdnanHodzic/auto-cpufreq/#auto-cpufreq-installer),have you tried installing auto-cpufreq using [Snap package](https://github.com/AdnanHodzic/auto-cpufreq/#snap-store)? N/A
- Have you tried [configuring auto-cpufreq](https://github.com/AdnanHodzic/auto-cpufreq/#configuring-auto-cpufreq)? Yes
- Have you tried suggestions in [troubleshooting section](https://github.com/AdnanHodzic/auto-cpufreq#troubleshooting)? Yes

### Error output:
```text
Add/paste error output in case of failed installation or other failing component
```
---

### System information:

Add/paste output of:

```
auto-cpufreq --debug
```
-------------------------------------------------------------------------------

Linux distro: LMDE 6 faye
Linux kernel: 6.1.0-17-amd64
Processor: Intel(R) Core(TM) i5 CPU       M 520  @ 2.40GHz
Cores: 4
Architecture: x86_64
Driver: acpi-cpufreq

------------------------------ Current CPU stats ------------------------------

CPU max frequency: 2400 MHz
CPU min frequency: 1199 MHz

Core	Usage	Temperature	Frequency
CPU0      1.0%        34 °C      2229 MHz
CPU1      5.0%        41 °C      2212 MHz
CPU2      2.0%        34 °C      2188 MHz
CPU3      2.0%        41 °C      2142 MHz

CPU fan speed: 0 RPM

auto-cpufreq version: 2.1.0 (git: 68dec52)

Python: 3.11.2
psutil package: 5.9.8
platform package: 1.0.8
click package: 8.1.7
distro package: 1.9.0

Computer type: Notebook
Battery is: charging

auto-cpufreq system resource consumption:
cpu usage: 0.0 %
memory use: 0.36 %

Total CPU usage: 5.8 %
Total system load: 0.77
Average temp. of all cores: 37.50 °C 

Currently using: performance governor
Currently turbo boost is: off```

Also please be descriptive about the issue you're reporting, i.e: what you tried & what's the expected behaviour.

---
I saw my min processor speed was still a bit high. I did the troubleshooting step on my grub file (https://github.com/AdnanHodzic/auto-cpufreq?tab=readme-ov-file#troubleshooting) but that didn't seem to make a difference. Any suggestions? Apologies if I missed anything. Thanks in advance!
 
![Screenshot from 2024-01-30 12-24-02](https://github.com/AdnanHodzic/auto-cpufreq/assets/71564494/46479df5-c046-4d29-9177-53442c267af6)

**Comment by shadeyg56** [comment]
`acpi-cpufreq` only exposes a few frequencies that can be used. To find the minimum you can run `cat /sys/devices/system/cpu/cpu0/cpufreq/scaling_min_freq`
To get a list of them all, run `cat /sys/devices/system/cpu/cpu0/scaling_available_frequencies`

**Comment by AdnanHodzic** [comment]
Closing the issue due to inactivity.
