### ISSUE TITLE
performance mode not working like a performance

### ISSUE THREAD

**Issue by gnuchanos** [AdnanHodzic/auto-cpufreq#681]
### Have you tried?
![2024-04-23-110044_1034x114_scrot](https://github.com/AdnanHodzic/auto-cpufreq/assets/117280480/d77c2414-30aa-432d-a6e0-8dd40b8bcd85)
![2024-04-23-110055_1027x768_scrot](https://github.com/AdnanHodzic/auto-cpufreq/assets/117280480/4c04e940-453c-4de1-bd90-28df221e16e1)
still working low cpu frequency why? why i can't 2.3 ghz?

### Error output:
```text
Add/paste error output in case of failed installation or other failing component
```
---

### System information:

Add/paste output of:

```
auto-cpufreq --debug
```

Linux distro: Arch Linux rolling n/a
Linux kernel: 6.8.7-zen1-1-zen
Processor: Intel(R) Core(TM) i3-2350M CPU @ 2.30GHz
Cores: 4
Architecture: x86_64
Driver: intel_cpufreq

------------------------------ Current CPU stats ------------------------------

CPU max frequency: 920 MHz
CPU min frequency: 800 MHz

Core	Usage	Temperature	Frequency
CPU0     78.4%        79 °C       474 MHz
CPU1     79.8%        79 °C       474 MHz
CPU2     82.0%        79 °C       459 MHz
CPU3     80.4%        79 °C       463 MHz

auto-cpufreq version: Version         : 2.2.0-2

Python: 3.11.8
psutil package: 5.9.8
platform package: 1.0.8
click package: 8.1.7
distro package: 1.9.0

Computer type: Laptop
Battery is: charging

auto-cpufreq system resource consumption:
cpu usage: 0.0 %
memory use: 0.5 %

Total CPU usage: 36.7 %
Total system load: 9.57
Average temp. of all cores: 79.00 °C 

Currently using: performance governor
Currently turbo boost is: on

---

**Comment by AdnanHodzic** [comment]
What exactly did you mean to say in this issue or what is the problem you're facing?

**Comment by gnuchanos** [comment]
If you look at the screenshot, you can understand what the problem is, but I removed this from my system loo late
