### ISSUE TITLE
auto-cpufreq Ubuntu 24.04

### ISSUE THREAD

**Issue by mh-saeed** [AdnanHodzic/auto-cpufreq#686]
I have heard that there are some [improvements](https://www.omgubuntu.co.uk/2024/04/ubuntu-24-04-battery-life-improvements) made for better battery health and backup in Ubuntu 24.04.
The question is, Do we still need auto-cpufeq in Ubuntu 24.04?

**Comment by AdnanHodzic** [comment]
>The question is, Do we still need auto-cpufeq in Ubuntu 24.04?

Absolutely, I've been running on 24.04. 

Not convinced try measuring how much battery life you get with and without auto-cpufreq. 

Closing the issue since it's more of a [question/discussion](https://github.com/AdnanHodzic/auto-cpufreq/discussions) then an issue.
