### ISSUE TITLE
Unable to copy to scripts/auto-cpufreq.service

### ISSUE THREAD

**Issue by srbhp** [AdnanHodzic/auto-cpufreq#7]
Unable to copy the scripts/auto-cpufreq.service file to 
/lib/systemd/system/auto-cpufreq.service in openSuse.

Correct path should be /usr/lib/systemd/system/auto-cpufreq.service. 

Thanks for the auto-cpufreq.

**Comment by aroundthfur** [comment]
PR ready here: https://github.com/AdnanHodzic/auto-cpufreq/pull/8

**Comment by AdnanHodzic** [comment]
@aroundthfur merged

@srbhp feel free to re-op[en this if the issue persists.
