### ISSUE TITLE
Getting TypeError when executing after installation

### ISSUE THREAD

**Issue by doehr** [AdnanHodzic/auto-cpufreq#715]
Hi all,

I've used the snap package of auto-cpufreq for some time. Today I uninstalled the snap package and used the recommended installation method:

> git clone https://github.com/AdnanHodzic/auto-cpufreq.git
> cd auto-cpufreq && sudo ./auto-cpufreq-installer

When running

> auto-cpufreq 

after installation I get the following error:

<pre>Traceback (most recent call last):
  File &quot;/opt/auto-cpufreq/venv/bin/auto-cpufreq&quot;, line 5, in &lt;module&gt;
    from auto_cpufreq.bin.auto_cpufreq import main
  File &quot;/opt/auto-cpufreq/venv/lib/python3.8/site-packages/auto_cpufreq/bin/auto_cpufreq.py&quot;, line 15, in &lt;module&gt;
    from auto_cpufreq.core import *
  File &quot;/opt/auto-cpufreq/venv/lib/python3.8/site-packages/auto_cpufreq/core.py&quot;, line 29, in &lt;module&gt;
    from auto_cpufreq.utils.config import config
  File &quot;/opt/auto-cpufreq/venv/lib/python3.8/site-packages/auto_cpufreq/utils/config.py&quot;, line 8, in &lt;module&gt;
    def find_config_file(args_config_file: str | None) -&gt; str:
TypeError: unsupported operand type(s) for |: &apos;type&apos; and &apos;NoneType&apos;</pre>

Uninstalling, rebooting and reinstalling was not successful. Any hints on how I can fix this issue? Huge thanks in advance.

**Comment by Angel-Karasu** [comment]
What is your python version ?
To found it run `python --version`

> Hi all,
> 
> I've used the snap package of auto-cpufreq for some time. Today I uninstalled the snap package and used the recommended installation method:
> 
> > git clone https://github.com/AdnanHodzic/auto-cpufreq.git
> > cd auto-cpufreq && sudo ./auto-cpufreq-installer
> 
> When running
> 
> > auto-cpufreq
> 
> after installation I get the following error:
> 
> Traceback (most recent call last):
>   File "/opt/auto-cpufreq/venv/bin/auto-cpufreq", line 5, in <module>
>     from auto_cpufreq.bin.auto_cpufreq import main
>   File "/opt/auto-cpufreq/venv/lib/python3.8/site-packages/auto_cpufreq/bin/auto_cpufreq.py", line 15, in <module>
>     from auto_cpufreq.core import *
>   File "/opt/auto-cpufreq/venv/lib/python3.8/site-packages/auto_cpufreq/core.py", line 29, in <module>
>     from auto_cpufreq.utils.config import config
>   File "/opt/auto-cpufreq/venv/lib/python3.8/site-packages/auto_cpufreq/utils/config.py", line 8, in <module>
>     def find_config_file(args_config_file: str | None) -> str:
> TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
> 
> Uninstalling, rebooting and reinstalling was not successful. Any hints on how I can fix this issue? Huge thanks in advance.

**Comment by doehr** [comment]
> What is your python version ? To found it run `python --version`
> 

Thanks for the quick reply. I get the following error:
<pre>bash: python: command not found</pre>

The following python versions are installed
<pre>python2           python3           python3.8         python3-config
python2.7         python3.13        python3.8-config  </pre>

**Comment by Angel-Karasu** [comment]
> > What is your python version ? To found it run `python --version`
> 
> Thanks for the quick reply. I get the following error:
> 
> bash: python: command not found
> 
> The following python versions are installed
> 
> python2           python3           python3.8         python3-config
> python2.7         python3.13        python3.8-config

Try `python3 --version`

**Comment by doehr** [comment]
The Python version is:
<pre>Python 3.8.10
</pre>

**Comment by Angel-Karasu** [comment]
Try to run `sudo update-alternatives --install /usr/bin/python python /usr/bin/python3.13 1` and retry to run `auto-cpufreq`
It forces to use python 3.13 instead python 3.8

**Comment by doehr** [comment]
I tried. Unfortunately it didn't work...

**Comment by Angel-Karasu** [comment]
Try to replace python to python3: `sudo update-alternatives --install /usr/bin/python python3 /usr/bin/python3.13 1`
And show the python version: `python3 --version`
If the version is still 3.8, the bug will persist, otherwise you can try running `auto-cpufreq`.

**Comment by Angel-Karasu** [comment]
The correction has been applied, wait until it is merged with the main branch or if you don't went to wait you can run `git clone -b origin https://github.com/Angel-Karasu/auto-cpufreq.git` and follow the installation

**Comment by doehr** [comment]
Hi, I upgraded to the latest Linux Mint version 21.3 and did a reinstall. Everything seems to work now. Thank you for you support!

**Comment by Angel-Karasu** [comment]
PR #716 is merged which should fix the issue, if problem persists, please feel free to re-open it
