### ISSUE TITLE
should we add Code Docs for Devs

### ISSUE THREAD

**Issue by PurpleWazard** [AdnanHodzic/auto-cpufreq#758]
so i had an idea for the devs on this project. since its been a while since ive been able to help with this, some stuff has changed. i thought there should be a markdown file or something that explains each function in brief or causal detail on how it works. and also how the project works as a whole. 

i think this would be beneficial to new devs. because they wouldn't have to figure out for them selves how certain parts work. also it would summarize what does what and how it does it.

idk if this is something yall would want. let me know.

**Comment by AdnanHodzic** [comment]
Absolutely, this would be amazing to have. Please go for it!

**Comment by PurpleWazard** [comment]
will do.
