### ISSUE TITLE
[Installation] shouldn't it remove old version when u install new one?

### ISSUE THREAD

**Issue by Red-Eyed** [AdnanHodzic/auto-cpufreq#77]
just built snapcraft, installed it
tried to look at `--monitor`, but it said that I should use `--log` instead

It means that installing new version doesn't remove old one.

@AdnanHodzic could you confirm?

**Comment by AdnanHodzic** [comment]
This happened because there was a daemon running which `auto-cpufreq --install` sets up. This was made as a preventive measure, for 2 instances of auto-cpufreq not to be running at the same time and thus giving you wrong results.
