### ISSUE TITLE
T480 wont charge after using battery config

### ISSUE THREAD

**Issue by Brandixz** [AdnanHodzic/auto-cpufreq#783]
### Fill out information requested in this template, without doing so issue will be ignored & closed!

I had used the Battery Config for my T480. Currently it doesn't have a external battery and only the internal battery. The configuration I added to /etc/auto-cpufreq.conf are as follows:

[battery]
enable_thresholds = true
start_threshold = 20
stop_threshold = 90 

When I would reboot the system with a charge below 90% it would not charge only indicating "Not Charging". I had to restart the battery using the methods in https://forums.lenovo.com/t5/ThinkPad-T400-T500-and-newer-T-series-Laptops/T480-plugged-in-not-charging-Solution/m-p/5049970 in order to restarting charging again. I repeated this command shortly after and rebooted the system and the same symptoms showed and repeated the battery reboot in order to get it charging again. 

*Note: in the .conf file that is the only lines I added to the .conf file. When I opened the .conf file it was blank.

### Have you tried? (Yes I did)

- [Searching through existing/closed issues](https://github.com/AdnanHodzic/auto-cpufreq/issues) to see if your bug has already been already submitted? 
- If installation failed with [auto-cpufreq-installer](https://github.com/AdnanHodzic/auto-cpufreq/#auto-cpufreq-installer),have you tried installing auto-cpufreq using [Snap package](https://github.com/AdnanHodzic/auto-cpufreq/#snap-store)?
- Have you tried [configuring auto-cpufreq](https://github.com/AdnanHodzic/auto-cpufreq/#configuring-auto-cpufreq)?
- Have you tried suggestions in [troubleshooting section](https://github.com/AdnanHodzic/auto-cpufreq#troubleshooting)?

### Error output: (none)
```text
Add/paste error output in case of failed installation or other failing component
```
---

### System information: (Haven't used)

Add/paste output of:

```
auto-cpufreq --debug

Also please be descriptive about the issue you're reporting, i.e: what you tried & what's the expected behaviour.

---

**Comment by kirmola** [comment]
how did you solved it @Brandixz

**Comment by Hikari2w2** [comment]
@Brandixz pls can you tell me how did you solve this issue?. I also have a T480.
