### ISSUE TITLE
The systemd log is being spammed by auto-cpufreq

### ISSUE THREAD

**Issue by marc0der** [AdnanHodzic/auto-cpufreq#82]
I've started using the tool and loving it so far. Good work!

After installation, the `auto-cpufreq` service is continually outputting the full payload of the `--log` command to the system logs. 

When tailing the logs with `journalctl --follow`, I see a continual stream of these log reports being dumped in the log every 5 seconds.

```
...
Aug 07 12:34:18 rocinante auto-cpufreq.service[561395]: ----------------------------- System information ------------------------------
Aug 07 12:34:18 rocinante auto-cpufreq.service[561395]: Linux distro: Manjaro Linux UNKNOWN version
Aug 07 12:34:18 rocinante auto-cpufreq.service[561395]: Linux kernel: 5.4.52-1-MANJARO
Aug 07 12:34:18 rocinante auto-cpufreq.service[561395]: Driver: intel_pstate
Aug 07 12:34:18 rocinante auto-cpufreq.service[561395]: Architecture: x86_64
Aug 07 12:34:18 rocinante auto-cpufreq.service[561395]: Processor: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
...
```
My system info:

```
               +
               #
              ###
             #####
             ######
            ; #####;            User: marco
           +##.#####            Hostname: rocinante
          +##########           Distro: Arch Linux
         #############;         Kernel: 5.4.52-1-MANJARO
        ###############+        Uptime: 10 days, 14:03
       #######   #######        Window Manager: i3
     .######;     ;###;`".      Desktop Environment:
    .#######;     ;#####.       Shell: /bin/zsh
    #########.   .########`     Terminal: screen-256color
   ######'           '######    Packages: 1588
  ;####                 ####;   CPU: Intel(R) Core(TM) i7-8650U CPU @ 1.90GHz
  ##'                     '##   RAM: 6717 MB / 15766 MB
 #'                         `#  Disk: 469GB / 989GB
```
Installed with snap:
```
snap     2.45.2-1
snapd    2.45.2-1
series   16
manjaro  -
kernel   5.4.52-1-MANJARO
```

Should this perhaps rather be a one-line summary whenever the state of cpu scaling is changed by the tool?

I also further noticed the continued references to a `/var/log/auto-cpufreq.log` file in the service descriptor and elsewhere, but this file never seems to be created. I tried creating it myself, but it still doesn't get populated with the logs.

I realise that these are just teething issues that still need to be sorted. Keep up the great work!

**Comment by AdnanHodzic** [comment]
First of all thanks :)

I remember this same thing was mentioned in #53. Hence, I think it would be a good think to address this issue in one of the future releases.

**Comment by marc0der** [comment]
Great stuff. Some further digging has revealed that all logging is done straight to standard out. Perhaps this issue could be circumvented using targeted logging using a logger library. I could look into this, but since python isn't my first language I'm not promising anything.

**Comment by AdnanHodzic** [comment]
Go for it, it would be amazing to see a PR from you :) Otherwise, even if you find a nice library that could be used for this purpose that would also be great.

**Comment by AdnanHodzic** [comment]
Released a fix as part of 1.2.3 version which is available in beta channel, install it by running:

```
sudo snap install auto-cpufreq --beta
```

After you confirm it's working as expected for you I'll promote it to stable channel, merge changes with master and close this issue.

**Comment by marc0der** [comment]
I just tried it out and it works perfectly :+1:

**Comment by AdnanHodzic** [comment]
Awesome, enjoy
